# ~/.config/starship.toml

[aws]
# keep the default

[conda]
symbol = " "

[dart]
# keep the default

[directory]
read_only = " "
truncation_length = 5

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = 'via [$symbol]($style)'

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
# keep the default

[hg_branch]
symbol = " "

[java]
symbol = " "
format = 'via [$symbol]($style)'

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
# keep the default

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
# keep the defaults!

[ruby]
symbol = " "

[rust]
# keep the defaults

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
format = 'via [$symbol]($style)'

[git_status]
disabled = false
