[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["-"] }
auto-format = true

[language-server.pylsp.config.plugins]
flake8 = { enabled = false }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
yapf = { enabled = false }
ruff = { enabled = true }


[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "toml"
auto-format = true
