[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "flake8", args = [""] }
language-servers = [{ name = "pyright" }, { name = "ruff-lsp" }]
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "toml"
auto-format = true
