name: doomemacs-config-build
on:
  push:
    tags: ["v*"]
    branches: ["*"]
jobs:
  build_and_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get install -y git zip
      - name: Install emacs28
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt-get install -y emacs28
      - name: Install doomemacs
        run: |
          git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
          ln -s $GITHUB_WORKSPACE/doom ~/.config/doom
          ~/.config/emacs/bin/doom install --no-env --no-fonts
      - name: ZIP the config
        run: |
          zip -r doomemacsconfig.zip ~/.config/emacs
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            doomemacsconfig.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
